/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafeGuiaTransportista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import sistemafeGuiaTransportista.Logica.LogGTRview;

/**
 *
 * @author kbarreda
 */
public class FrameGTRVer extends javax.swing.JFrame {

    public static String GuiaSerie = "";
    public static String GuiaNumero = "";

    public static String GuiaTraslado = "";
    public static String FechaEmision = "";

    public static String IdPlantaPartida = "";
    public static String UbigeoPartida = "";

    public static String IdPlantaLlegada = "";
    public static String UbigeoLlegada = "";

    public static List<String> RestidUbigeo = new ArrayList();
    public static List<String> RestDescripcion = new ArrayList();

    public static String PartidaDireccion = "";
    public static String PartidaIdDepart = "";
    public static String PartidaDescDepart = "";
    public static String PartidaIdProvincia = "";
    public static String PartidaDescProvinci = "";
    public static String PartidaIdDistrito = "";
    public static String PartidaDescDistrito = "";

    public static String LlegadaDireccion = "";
    public static String LlegadaIdDepart = "";
    public static String LlegadaDescDepart = "";
    public static String LlegadaIdProvincia = "";
    public static String LlegadaDescProvinci = "";
    public static String LlegadaIdDistrito = "";
    public static String LlegadaDescDistrito = "";

    public static String RemiteId = "";
    public static String RemiteNroid = "";
    public static String RemiteDescripcion = "";

    public static String Scop = "";

    public static List<String> GTRItemsId = new ArrayList();
    public static List<String> GTRItemsDesc = new ArrayList();
    public static List<String> GTRItemsUnidad = new ArrayList();
    public static List<String> GTRItemsCantidad = new ArrayList();

    public static String ChoferId = "";
    public static String ChoferDescrip = "";

    public static String VehiculoTracto = "";
    public static String VehiculoCisterna = "";
    public static String VehiculoMarca = "";

    public FrameGTRVer() throws Exception {
        initComponents();

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(153, 51, 0));
        headerRenderer.setForeground(new Color(255, 255, 255));
        headerRenderer.setFont(new Font("Serif", Font.BOLD, 15));
        headerRenderer.setPreferredSize(new Dimension(28, 28));
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField17 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField33 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 20));
        setMinimumSize(new java.awt.Dimension(830, 470));
        setUndecorated(true);
        setSize(new java.awt.Dimension(830, 698));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 830, 20));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GUÍA DE REMISIÓN TRANSPORTISTA");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 400, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(33, 63, 86));
        jLabel17.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 63, 86));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DIRECCIÓN DE PARTIDA");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 20));

        jSeparator2.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator2.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator2.setPreferredSize(null);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 390, 10));

        jSeparator3.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator3.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator3.setPreferredSize(null);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 390, 10));

        jTextField17.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField17.setFocusable(false);
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 290, 22));

        jLabel40.setBackground(new java.awt.Color(33, 63, 86));
        jLabel40.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(33, 63, 86));
        jLabel40.setText("DEPARTAMENTO  :");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 100, 22));

        jTextField18.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField18.setFocusable(false);
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 290, 22));

        jLabel41.setBackground(new java.awt.Color(33, 63, 86));
        jLabel41.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(33, 63, 86));
        jLabel41.setText("PROVINCIA           :");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, 22));

        jLabel42.setBackground(new java.awt.Color(33, 63, 86));
        jLabel42.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(33, 63, 86));
        jLabel42.setText("DISTRITO               :");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 22));

        jTextField20.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField20.setFocusable(false);
        jPanel3.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 290, 22));

        jLabel43.setBackground(new java.awt.Color(33, 63, 86));
        jLabel43.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(33, 63, 86));
        jLabel43.setText("PROVINCIA           :");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 22));

        jLabel44.setBackground(new java.awt.Color(33, 63, 86));
        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(33, 63, 86));
        jLabel44.setText("DEPARTAMENTO  :");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 22));

        jLabel45.setBackground(new java.awt.Color(33, 63, 86));
        jLabel45.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(33, 63, 86));
        jLabel45.setText("FECHA DE EMISIÓN     :");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        jTextField21.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField21.setFocusable(false);
        jPanel3.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 290, 22));

        jTextField22.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField22.setFocusable(false);
        jPanel3.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 290, 22));

        jTextField23.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField23.setFocusable(false);
        jPanel3.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, 22));

        jTextField24.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField24.setFocusable(false);
        jPanel3.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, 22));

        jLabel46.setBackground(new java.awt.Color(33, 63, 86));
        jLabel46.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(33, 63, 86));
        jLabel46.setText("DISTRITO               :");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 22));

        jLabel47.setBackground(new java.awt.Color(33, 63, 86));
        jLabel47.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(33, 63, 86));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("ESTACIÓN DE SERVICIOS PETRO WORLD S.A.C.");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 390, 20));

        jLabel48.setBackground(new java.awt.Color(33, 63, 86));
        jLabel48.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(33, 63, 86));
        jLabel48.setText("PTO. DE SALIDA   :");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 22));

        jLabel49.setBackground(new java.awt.Color(33, 63, 86));
        jLabel49.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(33, 63, 86));
        jLabel49.setText("FECHA DE TRASLADO :");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 20));

        jSeparator8.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator8.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator8.setPreferredSize(null);
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 390, 10));

        jSeparator9.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator9.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator9.setPreferredSize(null);
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 390, 10));

        jLabel50.setBackground(new java.awt.Color(33, 63, 86));
        jLabel50.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(33, 63, 86));
        jLabel50.setText("PTO. DE LLEGADA:");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, 22));

        jLabel51.setBackground(new java.awt.Color(33, 63, 86));
        jLabel51.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(33, 63, 86));
        jLabel51.setText("SERIE-NRO:");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 70, 20));

        jLabel52.setBackground(new java.awt.Color(33, 63, 86));
        jLabel52.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(33, 63, 86));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("DIRECCIÓN DE LLEGADA");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 390, 20));

        jLabel53.setBackground(new java.awt.Color(33, 63, 86));
        jLabel53.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(33, 63, 86));
        jLabel53.setText("RUC: ");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 40, 20));

        jLabel54.setBackground(new java.awt.Color(33, 63, 86));
        jLabel54.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(33, 63, 86));
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 140, 20));

        jLabel55.setBackground(new java.awt.Color(33, 63, 86));
        jLabel55.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(33, 63, 86));
        jLabel55.setText("20514636843");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 110, 20));

        jLabel60.setBackground(new java.awt.Color(33, 63, 86));
        jLabel60.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(33, 63, 86));
        jLabel60.setText("RUC/DNI                :");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 22));

        jTextField28.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField28.setFocusable(false);
        jPanel3.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 290, 22));

        jLabel61.setBackground(new java.awt.Color(33, 63, 86));
        jLabel61.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(33, 63, 86));
        jLabel61.setText("RAZÓN SOCIAL    :");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 22));

        jTextField29.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField29.setFocusable(false);
        jPanel3.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 290, 22));

        jLabel18.setBackground(new java.awt.Color(33, 63, 86));
        jLabel18.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(33, 63, 86));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("REMITENTE");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 390, 20));

        jSeparator5.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator5.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator5.setPreferredSize(null);
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 390, 10));

        jSeparator6.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator6.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator6.setPreferredSize(null);
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 390, 10));

        jLabel62.setBackground(new java.awt.Color(33, 63, 86));
        jLabel62.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(33, 63, 86));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("DESTINATARIO");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 390, 20));

        jTextField30.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField30.setFocusable(false);
        jPanel3.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 290, 22));

        jLabel63.setBackground(new java.awt.Color(33, 63, 86));
        jLabel63.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(33, 63, 86));
        jLabel63.setText("RAZÓN SOCIAL    :");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 22));

        jLabel64.setBackground(new java.awt.Color(33, 63, 86));
        jLabel64.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(33, 63, 86));
        jLabel64.setText("RUC/DNI                :");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 100, 22));

        jTextField31.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField31.setFocusable(false);
        jPanel3.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 290, 22));

        jTextField32.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField32.setFocusable(false);
        jPanel3.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 290, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "MEDIDA", "CANTIDAD"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 810, 150));

        jTextField33.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField33.setFocusable(false);
        jPanel3.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 290, 22));

        jLabel65.setBackground(new java.awt.Color(33, 63, 86));
        jLabel65.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(33, 63, 86));
        jLabel65.setText("LICENCIA              :");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 100, 22));

        jLabel66.setBackground(new java.awt.Color(33, 63, 86));
        jLabel66.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(33, 63, 86));
        jLabel66.setText("NOMBRE               :");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 22));

        jTextField34.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField34.setFocusable(false);
        jPanel3.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 290, 22));

        jSeparator7.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator7.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator7.setPreferredSize(null);
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 390, 10));

        jLabel19.setBackground(new java.awt.Color(33, 63, 86));
        jLabel19.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 63, 86));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CHOFER");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 390, 20));

        jTextField35.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField35.setFocusable(false);
        jPanel3.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 290, 22));

        jLabel67.setBackground(new java.awt.Color(33, 63, 86));
        jLabel67.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(33, 63, 86));
        jLabel67.setText("TACTO                 :");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 100, 22));

        jLabel68.setBackground(new java.awt.Color(33, 63, 86));
        jLabel68.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(33, 63, 86));
        jLabel68.setText("CAMIÓN              :");
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 100, 22));

        jTextField36.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField36.setFocusable(false);
        jPanel3.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 290, 20));

        jSeparator10.setBackground(new java.awt.Color(33, 63, 86));
        jSeparator10.setMinimumSize(new java.awt.Dimension(0, 5));
        jSeparator10.setPreferredSize(null);
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 390, 10));

        jLabel20.setBackground(new java.awt.Color(33, 63, 86));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(33, 63, 86));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("UNIDAD DE TRANSPORTE");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 390, 20));

        jLabel69.setBackground(new java.awt.Color(33, 63, 86));
        jLabel69.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(33, 63, 86));
        jLabel69.setText("MARCA                :");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 100, 22));

        jTextField37.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField37.setFocusable(false);
        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 290, 22));

        jLabel70.setBackground(new java.awt.Color(33, 63, 86));
        jLabel70.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(33, 63, 86));
        jLabel70.setText("SCOP                     :");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, 30));

        jTextField38.setBackground(new java.awt.Color(204, 255, 255));
        jTextField38.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField38.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 290, 30));

        jTextField25.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField25.setFocusable(false);
        jPanel3.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 290, 22));

        jTextField26.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTextField26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField26.setFocusable(false);
        jPanel3.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 260, 22));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static boolean esNumero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed
    public void IgualarUbigeoPartida() {
        PartidaIdDepart = RestidUbigeo.get(0);
        PartidaDescDepart = RestDescripcion.get(0);
        PartidaIdProvincia = RestidUbigeo.get(1);
        PartidaDescProvinci = RestDescripcion.get(1);
        PartidaIdDistrito = RestidUbigeo.get(2);
        PartidaDescDistrito = RestDescripcion.get(2);
    }

    public void IgualarUbigeoLlegada() {
        LlegadaIdDepart = RestidUbigeo.get(0);
        LlegadaDescDepart = RestDescripcion.get(0);
        LlegadaIdProvincia = RestidUbigeo.get(1);
        LlegadaDescProvinci = RestDescripcion.get(1);
        LlegadaIdDistrito = RestidUbigeo.get(2);
        LlegadaDescDistrito = RestDescripcion.get(2);
    }

    public void ConsultasGTRver() throws Exception {
        LogGTRview.VistaLog();
        
        

    }

    public void LLenarCampos() {
        jTextField26.setText(GuiaTraslado);
        jTextField23.setText(FechaEmision);
        jLabel54.setText("G" + GuiaSerie.substring(1, 4
        ) + "-" + GuiaNumero);
        jTextField21.setText(PartidaDireccion);
        jTextField22.setText(PartidaDescDepart);
        jTextField23.setText(PartidaDescProvinci);
        jTextField24.setText(PartidaDescDistrito);
        jTextField29.setText(RemiteDescripcion);
        jTextField28.setText(RemiteNroid);
        jTextField30.setText(RemiteDescripcion);
        jTextField31.setText(RemiteNroid);
        jTextField38.setText(Scop);
        jTextField17.setText(LlegadaDireccion);
        jTextField18.setText(LlegadaDescDepart);
        jTextField32.setText(LlegadaDescProvinci);
        jTextField20.setText(LlegadaDescDistrito);
        NewJFrameinsertablasa();
        jTextField34.setText(ChoferDescrip);
        jTextField33.setText(ChoferId);
        jTextField35.setText(VehiculoTracto);
        jTextField36.setText(VehiculoCisterna);
        jTextField37.setText(VehiculoMarca);
    }

    public void LimpiarVariables() {
        GuiaTraslado = "";
        FechaEmision = "";
        IdPlantaPartida = "";
        UbigeoPartida = "";
        IdPlantaLlegada = "";
        UbigeoLlegada = "";
        RestidUbigeo.clear();
        RestDescripcion.clear();
        PartidaDireccion = "";
        PartidaIdDepart = "";
        PartidaDescDepart = "";
        PartidaIdProvincia = "";
        PartidaDescProvinci = "";
        PartidaIdDistrito = "";
        PartidaDescDistrito = "";
        LlegadaDireccion = "";
        LlegadaIdDepart = "";
        LlegadaDescDepart = "";
        LlegadaIdProvincia = "";
        LlegadaDescProvinci = "";
        LlegadaIdDistrito = "";
        LlegadaDescDistrito = "";
        RemiteId = "";
        RemiteNroid = "";
        RemiteDescripcion = "";
        Scop = "";
        GTRItemsId.clear();
        GTRItemsUnidad.clear();
        GTRItemsDesc.clear();
        GTRItemsUnidad.clear();
        GTRItemsCantidad.clear();

        ChoferId = "";
        ChoferDescrip = "";

        VehiculoTracto = "";
        VehiculoCisterna = "";
        VehiculoMarca = "";
    }

    public void NewJFrameinsertablasa() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[4];
        for (int i = 0; i < GTRItemsId.size(); i++) {
            rowData[0] = GTRItemsId.get(i);
            rowData[1] = GTRItemsDesc.get(i);
            rowData[2] = GTRItemsUnidad.get(i);
            rowData[3] = GTRItemsCantidad.get(i);
            model.addRow(rowData);
        }

    }

    public void Removerinsertablasa() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGTRVer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGTRVer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGTRVer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGTRVer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameGTRVer().setVisible(true);

                } catch (Exception ex) {
                    Logger.getLogger(FrameGTRVer.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    // End of variables declaration//GEN-END:variables
}
