
package sistemafe;

import LogicaSql.LogEnviar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class DialogInsertTicket extends javax.swing.JFrame {

    public static String DlCia = "";
    public static String DlPlanta = "";
    public static String DlPlantaDescrip = "";
    public static String DlComprobante = "";
    public static String DlFecha = "";
    public static String DlTicket = "";
    public static String DlTipoDocument = ""; //llenar un tipo de documento

    public DialogInsertTicket() {
        initComponents();
        LlenarCampos();
    }

    public void LlenarCampos() {
        jTextField7.setText(DlCia + "        " + DlPlanta+" - "+DlPlantaDescrip);
        jTextField8.setText(DlComprobante);
        jTextField5.setText(DlFecha);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField5.setEditable(false);
        jTextField1.requestFocusInWindow();
    }

    public void BorrarDl() {
        DlCia = "";
        DlPlanta = "";
        DlComprobante = "";
        DlFecha = "";
        DlTicket = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel(); //ESTADO DEL ARCHIVO
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();//TODO para el boton INSERTAR TICKET
        jButton3 = new javax.swing.JButton();//TODO para el boton CAMBIAR EL ESTADO DEL ERROR

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 130));
        setMinimumSize(new java.awt.Dimension(830, 470));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(828, 469));
        setSize(new java.awt.Dimension(830, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 63, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Insertar Ticket");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Comprobante :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 130, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Ticket             :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); 
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Fecha             :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); 
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Cia - planta    :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, 30));

        
//TODO escucha para cuando se hace enter al ingresar un nuevo ticket
        /*jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        */
        
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 300, 30));

        jTextField5.setBackground(new java.awt.Color(33, 63, 86));
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 300, 30));

        jTextField7.setBackground(new java.awt.Color(33, 63, 86));
        jTextField7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 300, 30));

        jTextField8.setBackground(new java.awt.Color(33, 63, 86));
        jTextField8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 300, 30));
        
//TODO bloque que CAMBIAR EL ESTADO DEL PEDIDO
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        jButton3.setText("Validar Registro");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        
        
//TODO bloque que genera el boton CANCELAR
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        jButton1.setText("Cancelar registro");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        
//TODO bloque que genera el boton INSERTAR TICKET
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        jButton2.setText("Insertar Ticket");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        
//TODO coordenadas del boton CANCELAR REGISTRO
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 160, 30));
        
//TODO coordenadas del boton INSERTAR TICKET
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 160, 30));
        
//cambiar estado del archivo
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 470));

        pack();
    }
    
    
//TODO metodo que se ejecuta cuando se hace se da click en el boton CANCELAR REGISTRO
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        FrameAdminReporte.Met = "recuperar";
        FrameAdminReporte abrir;
        try {
            abrir = new FrameAdminReporte();
            abrir.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(DialogInsertTicket.class.getName()).log(Level.SEVERE, null, ex);
        }


    }
    

//TODO metodo que se ejecuta cuando se hace se da click en el boton INSERTAR TICKET
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
    	clickEnter();
    }
    
    //TODO metodo para cambiar el estado del pedido
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {
    	ClickModify();
    }
    
//TODO metodo que se ejecuta cuando se hace ENTER
    /*private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
    	clickEnter();
    }
	*/
   
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogInsertTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogInsertTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogInsertTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogInsertTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogInsertTicket().setVisible(true);
            }
        });
    }
    
    
//METODO PARA CAMBIAR EL ESTADO DEL ARCHIVO
    private void ClickModify() {
    	
    	int response = JOptionPane.showConfirmDialog(null, "¿Estas seguro?", "Modificar", JOptionPane.YES_NO_OPTION);
    	if(response == JOptionPane.YES_OPTION) {
    		String fecha = DlFecha;
    		String tipoD = DlTipoDocument;
    		String comprobante = DlComprobante;
    		String cia = DlCia.substring(0,2);
            String serie = "0" + DlComprobante.substring(1, 4);
            String Nro = DlComprobante.substring(5, 13);
    		try {
                LogEnviar.ModificarCode(fecha, cia, Nro, serie,tipoD, comprobante);
                JOptionPane.showMessageDialog(null, "Se modifico el comprobante: "+ comprobante);
                FrameAdminReporte.Met = "noenviados";
                FrameAdminReporte abrir;
                try {
                    abrir = new FrameAdminReporte();
                    abrir.setVisible(true);
                    this.setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(DialogInsertTicket.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(DialogInsertTicket.class.getName()).log(Level.SEVERE, null, ex);
            }
    	}else {
    		
    	}
    	
    	
    }
    
    
//TODO metodo que se ejecuta ya sea cuando se hace click en el boton INSERTAR TICKET
    private void clickEnter() {
    	String Ticket = jTextField1.getText();

    	if (Ticket.length() == 0 ){
            JOptionPane.showMessageDialog(null, "No ha introducido ningun ticket", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
        }
    	else if (Ticket.length() > 36) {
            JOptionPane.showMessageDialog(null, "El valor introducido no puede contener más de 36 caracteres", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String Tipo = DlComprobante.substring(0, 1);
            String Serie = "0" + DlComprobante.substring(1, 4);
            String Nro = DlComprobante.substring(5, 13);
            String Tipoconver = "";
            if ("F".equals(Tipo)) {
                Tipoconver = "FAC";
            } else if ("B".equals(Tipo)) {
                Tipoconver = "BOL";
            } else if ("N".equals(Tipo)) {
                Tipoconver = "n-c";
            } else {
            	
            }
            
            try {
                LogEnviar.InsertarTokentSQL(Ticket, DlCia, DlPlanta, Serie, Nro, Tipoconver);
            } catch (SQLException ex) {
                Logger.getLogger(DialogInsertTicket.class.getName()).log(Level.SEVERE, null, ex);
            }
            FrameAdminReporte.Met = "noenviados";
            FrameAdminReporte abrir;
            try {
                abrir = new FrameAdminReporte();
                abrir.setVisible(true);
                this.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(DialogInsertTicket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    

// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;//TODO para el boton cancelar registro
    private javax.swing.JButton jButton3; //TODO para cambiar el estado del registro
    private javax.swing.JLabel jLabel19; //label para cambiar el estado del pedido
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
