/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SisfactPoo;

import sistemafe.*;
import Datos.Datos;
import Logica.CellRenderer;
import LogicaSql.LogReporte;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author kbarreda
 */
public class FrameMigraXml extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    FrameLogin FL = new FrameLogin();
    Date StringFechaIni = null;
    Date StringFechaFin = null;
    public static List<String> ListFecha = new ArrayList();
    public static List<String> ListDoc = new ArrayList();
    public static List<String> ListCod = new ArrayList();
    public static List<String> ListDes = new ArrayList();
    public static ArrayList<Doc> list = new ArrayList();

    public static String ParamPlanta;
    public static String ParamFechaIni;
    public static String ParamFechaFin;
    public static String PlantaDescrip;
    
    public static String sFechaSistema;

    public static Integer ContarErrores = 0;
    public static Integer ContarSinEnviar = 0;
    public static Integer ContarEspera = 0;
    public static Integer ContarBajas = 0;
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo XMl", "xml");

    public FrameMigraXml() {
        initComponents();
        setCellRender(jTable2);
        jLabel4.setText(Datos.FeUsuario + " - " + "Cerrar sesión");
        if ("01".equals(Datos.FeCiaCod)) {
            jLabel15.setText("Compañia: Petróleos de América");
        } else if ("06".equals(Datos.FeCiaCod)) {
            jLabel15.setText("Compañia: Hidrocarburos del mundo");
        } else {
            jLabel15.setText("La compañia no tiene autorización");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 130));
        setMinimumSize(new java.awt.Dimension(830, 470));
        setUndecorated(true);
        setSize(new java.awt.Dimension(830, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Factura", "Fecha", "Estado", "Proveedor"
            }
        ));
        jTable2.setShowHorizontalLines(true);
        jTable2.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(40);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(1).setMinWidth(100);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(2).setMinWidth(75);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(75);
            jTable2.getColumnModel().getColumn(3).setMinWidth(120);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 400));

        
        if("SCOPE".equals(Datos.FOperacion)) {
        	
			jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
		    jLabel15.setForeground(new java.awt.Color(28, 59, 89));
		    jLabel15.setText("-");
		    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 30));
		
		    jButton5.setBackground(new java.awt.Color(255, 255, 255));
		    jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
		    jButton5.setForeground(new java.awt.Color(204, 204, 0));
		    /*ACÁ VA LA IMAGEEEEEEEEEEEEN ->   */
		    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenMigraciones2/edit-file-icon.png"))); // NOI18N
		    jButton5.setBorder(null);
		    jButton5.setBorderPainted(false);
		    jButton5.setContentAreaFilled(false);
		    jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		    jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
		        public void mouseClicked(java.awt.event.MouseEvent evt) {
		            //BOTON 10
		        	jButton10MouseClicked(evt);
		        }
		    });
		    jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, 50));
	        
        }else {
        
			jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
		    jLabel15.setForeground(new java.awt.Color(28, 59, 89));
		    jLabel15.setText("-");
		    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 30));
		
		    jButton5.setBackground(new java.awt.Color(255, 255, 255));
		    jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
		    jButton5.setForeground(new java.awt.Color(204, 204, 0));
		    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMigraciones/icons8_Plus_50px_1.png"))); // NOI18N
		    jButton5.setBorder(null);
		    jButton5.setBorderPainted(false);
		    jButton5.setContentAreaFilled(false);
		    jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		    jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
		        public void mouseClicked(java.awt.event.MouseEvent evt) {
		            jButton5MouseClicked(evt);
		        }
		    });
		    jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, 50));
        	
        }
        

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 590, 470));

        jPanel3.setBackground(new java.awt.Color(33, 63, 86));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMigraciones/icons8_XML_52px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 80));

        jLabel4.setBackground(new java.awt.Color(16, 54, 80));
        jLabel4.setFont(new java.awt.Font("BrowalliaUPC", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Male_User_52px.png"))); // NOI18N
        jLabel4.setText("-");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        
        
	        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));
	        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 10));
	        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 10));
	
	        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
	        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
	
	        jLabel3.setBackground(new java.awt.Color(16, 54, 80));
	        jLabel3.setFont(new java.awt.Font("BrowalliaUPC", 1, 20)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMigraciones/icons8_Add_List_52px.png"))); // NOI18N
	        jLabel3.setToolTipText("");
	        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jLabel3MouseClicked(evt);
	            }
	        });
	        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));
        
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 90, 70));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 70));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setBorder(null);
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(16, 54, 80));
        jLabel7.setFont(new java.awt.Font("BrowalliaUPC", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_CancelREPORT.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 90, 70));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Errores:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 70));

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));
        jPanel5.setBorder(null);
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(16, 54, 80));
        jLabel6.setFont(new java.awt.Font("BrowalliaUPC", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Email_Send_50pxREPORTE.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        if("SCOPE".equals(Datos.FOperacion)) {
        	jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 90, 70));

            jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(255, 255, 255));
            jLabel13.setText("Actualizados:");
            jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

            jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 70));
        }else {
        	jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 90, 70));

            jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(255, 255, 255));
            jLabel13.setText("Migrados:");
            jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

            jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 70));
        }
        	
        

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        FrameLogin abrir = new FrameLogin();
        Datos.FOperacion = "";
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        FrameEnviar abrir = new FrameEnviar();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        //add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        if ("La compañia no tiene autorización".equals(jLabel15.getText())) {
               JOptionPane.showMessageDialog(null, "La compañia no tiene autorización", "Atención !", JOptionPane.ERROR_MESSAGE);         
        } else {
            JFileChooser filechoser = new JFileChooser();
            filechoser.setMultiSelectionEnabled(true);
            filechoser.setFileFilter(filtro);
            int opcion = filechoser.showOpenDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                borrar();
                for (File items : filechoser.getSelectedFiles()) {
                    LogMigraXml.MigraXml(items);
                }
            }
            jLabel19.setText("Última migración:"+sFechaSistema);
            NewJFrameinsertablasa();
        }

    }//GEN-LAST:event_jButton5MouseClicked
    
    
    //APLICACION PARA ACTUALIZAR EL SCOP
    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        if ("La compañia no tiene autorización".equals(jLabel15.getText())) {
               JOptionPane.showMessageDialog(null, "La compañia no tiene autorización", "Atención !", JOptionPane.ERROR_MESSAGE);         
        } else {
            JFileChooser filechoser = new JFileChooser();
            filechoser.setMultiSelectionEnabled(true);
            filechoser.setFileFilter(filtro);
            int opcion = filechoser.showOpenDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                borrar();
                for (File items : filechoser.getSelectedFiles()) {
                    LogMigraXml.MigraXml(items);
                }
            }
            jLabel19.setText("Última migración:"+sFechaSistema);
            NewJFrameinsertablasa();
        }

    }//GEN-LAST:event_jButton5MouseClicked
    
    public class Doc {

        public String id;
        public String FEdoc;
        public String FEcod;
        public String FEdes;

        public Doc(String Id, String FEdoc, String FEcod, String FEdes) {
            this.id = Id;
            this.FEdoc = FEdoc;
            this.FEcod = FEcod;
            this.FEdes = FEdes;
        }
    }

    public ArrayList MetListErrores() {
        Integer IntFor = ListDoc.size();

        for (int factor = 1; factor <= IntFor; factor++) {
            Integer ds = factor - 1;
            Doc u1 = new Doc(ListDoc.get(ds), ListFecha.get(ds), ListCod.get(ds), ListDes.get(ds));
            list.add(u1);
        }
        return list;
    }

    public void NewJFrameinsertablasa() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        ArrayList<Doc> list = MetListErrores();
        Object rowData[] = new Object[5];
        int ccount = 0;
        int cmigrados = 0;
        int cerrores = 0;
        for (int i = 0; i < list.size(); i++) {
            ccount = i + 1;
            if ("Error".equals(list.get(i).FEcod)) {
                cerrores++;
            }
            else if("Duplicado".equals(list.get(i).FEcod)){
                cerrores++;
            }
            else {
                cmigrados++;
            }
            rowData[0] = ccount;
            rowData[1] = list.get(i).id;
            rowData[2] = list.get(i).FEdoc;
            rowData[3] = list.get(i).FEcod;
            rowData[4] = list.get(i).FEdes;
            model.addRow(rowData);
        }
        jLabel11.setText(String.valueOf(ccount));
        jLabel5.setText(String.valueOf(cmigrados));
        jLabel1.setText(String.valueOf(cerrores));
    }

    public void Removerinsertablasa() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    /**
     * @param table
     * @param args the command line arguments
     */
    public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
    }

    public void RecuperarDatos() throws ParserConfigurationException, SAXException, IOException, ParseException, Exception {

    }

    public void borrar() {
        ContarErrores = 0;
        ContarSinEnviar = 0;
        ContarEspera = 0;
        ContarBajas = 0;
        list.clear();
        ListDes.clear();
        ListFecha.clear();
        ListCod.clear();
        ListDoc.clear();
        ContarSinEnviar = 0;
        ContarErrores = 0;
        ContarEspera = 0;
        jLabel19.setText("");
        Removerinsertablasa();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMigraXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMigraXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMigraXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMigraXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameMigraXml().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
